### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sikmir** [Alexey-T/ATSynEdit#388]
```sh
cudatext> (3104) Compiling atsynedit_canvasproc_text_gtk3.pas
cudatext> /build/source/ATSynEdit/atsynedit/atsynedit_canvasproc_text_gtk3.pas(165,28) Error: (4025) Incompatible type for arg no. 1: Got "LAZCAIRO1.Pcairo_t", expected "CAIRO.Pcairo_t"
cudatext> /nix/store/sx0vkzalyjv8zn92g5rsp6szcp5464y8-fpc-3.2.2/lib/fpc/3.2.2/units/x86_64-linux/cairo/cairo.ppu:cairo.pp(650,11) Hint: (5039) Found declaration: cairo_font_extents(Pcairo_t;Pcairo_font_extents_t); CDecl;
cudatext> atsynedit_canvasproc_text_gtk3.pas(203) Fatal: (10026) There were 1 errors compiling module, stopping
cudatext> Fatal: (1018) Compilation aborted
cudatext> Error: /nix/store/sx0vkzalyjv8zn92g5rsp6szcp5464y8-fpc-3.2.2/bin/ppcx64 returned an error exitcode
cudatext> Error: (lazarus) Compile package atsynedit_package 2.28: stopped with exit code 1
cudatext> Error: (lazbuild) "atsynedit_package 2.28": compilation failed
```

Caused by https://github.com/Alexey-T/ATSynEdit/commit/7d3b51dc4e8ad89ec24900baf718a5ecd66b0c36

**Comment by Alexey-T** [comment]
I use FPC 3.2.3 and Lazarus 4.99 ie git main. What versions do you use?

**Comment by sikmir** [comment]
Lazarus 4.8-0 and FPC 3.2.2

**Comment by Alexey-T** [comment]
maybe smth is different in ide 4.8 versus ide 4.99. to check for me.
